language: go

# Required for coverage.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

# Get deps, build, test, and ensure the code is gofmt'ed.
script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - test -z "$(gofmt -d .)"
 - goveralls -coverprofile=gover.coverprofile -service=travis-ci
